/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'checkIn' : Time,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'checkOut' : Time,
  'phone' : string,
  'roomType' : string,
}
export interface SpecialOffer {
  'title' : string,
  'active' : boolean,
  'description' : string,
  'discountPercentage' : bigint,
  'validUntil' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addSpecialOffer' : ActorMethod<[string, string, bigint, Time], undefined>,
  'getActiveOffers' : ActorMethod<[], Array<SpecialOffer>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getInquiryCount' : ActorMethod<[], bigint>,
  'submitInquiry' : ActorMethod<
    [string, string, string, Time, Time, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];