/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const SpecialOffer = IDL.Record({
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'discountPercentage' : IDL.Nat,
  'validUntil' : Time,
});
export const Inquiry = IDL.Record({
  'checkIn' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'checkOut' : Time,
  'phone' : IDL.Text,
  'roomType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSpecialOffer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, Time], [], []),
  'getActiveOffers' : IDL.Func([], [IDL.Vec(SpecialOffer)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, Time, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const SpecialOffer = IDL.Record({
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'discountPercentage' : IDL.Nat,
    'validUntil' : Time,
  });
  const Inquiry = IDL.Record({
    'checkIn' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'checkOut' : Time,
    'phone' : IDL.Text,
    'roomType' : IDL.Text,
  });
  
  return IDL.Service({
    'addSpecialOffer' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, Time], [], []),
    'getActiveOffers' : IDL.Func([], [IDL.Vec(SpecialOffer)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };